# Generated by Django 2.2.7 on 2019-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('rent_amount', models.IntegerField()),
            ],
        ),
    ]
