# Generated by Django 2.2.6 on 2019-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('propertyName', models.CharField(max_length=120)),
                ('propertAddress', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=10)),
                ('bhk', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
