# Generated by Django 2.2.7 on 2019-11-21 17:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('propertyName', models.CharField(max_length=120)),
                ('propertyAddress', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('bhk', models.IntegerField()),
                ('societyName', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('propertyType', models.CharField(max_length=100)),
                ('moreData', jsonfield.fields.JSONField()),
            ],
        ),
    ]
