# Generated by Django 2.2.6 on 2019-10-14 12:46

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20191014_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='moreData',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
