# Generated by Django 2.2.6 on 2019-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_moredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='moreData',
            field=models.TextField(blank=True),
        ),
    ]
