# Generated by Django 2.2.6 on 2019-10-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20191014_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='propId',
        ),
    ]
