# Generated by Django 2.2.6 on 2019-10-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20191015_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
