# Generated by Django 2.2.6 on 2019-10-25 06:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20191017_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='moreDataString',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propId',
        ),
        migrations.AddField(
            model_name='property',
            name='moreData',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='societyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyAddress',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
