# Generated by Django 2.2.6 on 2019-11-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191113_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
